name: build-and-push
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
        id: tag_name
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        env: |
          VERSION: ${{ steps.tag_name.outputs.VERSION }}
      - name: Here we build an image
        run: 
          echo "docker build . -t deep-lesion:$VERSION"
      - name: Here we push an image
        run: 
          echo "push image to registry"
