name: build-and-push
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
      - name: Extract tag name
        id: vars
        run: 
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
       - name: Check output
       env:
         RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
       run: |
         echo $RELEASE_VERSION
         echo ${{ steps.vars.outputs.tag }}
         echo ${{ steps.vars.outputs }}
      - name: Here we build an image
        run: 
          echo "docker build . -t deep-lesion:$RELEASE_VERSION"
      - name: Here we push an image
        run: 
          echo "push image to registry"
