name: build-and-push
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
      - name: Extract tag name
        id: vars
        run: 
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Here we build an image
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: 
          docker build . -t deep-lesion:$RELEASE_VERSION
      - name: Here we push an image
        run: 
          echo "push image to registry"
