name: build-and-push
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract tag name
        id: vars
        run: 
          echo ::set-output name=TAG::${GITHUB_REF#refs/*/}
        env:
          VERSION: ${{ steps.vars.outputs.TAG }}
      - name: Here we build an image
        run: 
          echo "docker build . -t deep-lesion:$VERSION"
      - name: Here we push an image
        run: 
          echo "push image to registry"
