name: run-tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        pip install pylint
        pip install flake8
        pip install bandit
    - name: Lint with flake8
      run: |
        echo "Run flake8 and display statistics"
        flake8 . -v --count --show-source --max-line-length=120 --select=E,F,W,C --statistics
        echo "Get flake8 bug-report"
        flake8 . --bug-report
    - name: Lint with pylint
      run: |
        pylint --rcfile=setup_linters.cfg *.py
    - name: Lint with bandit
      run: |
        bandit -r --ini setup_linters.cfg *.py
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
    - name: Run PyTests
      run: |
        export PYTHONPATH=$(pwd)
        pytest tests      
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
    - name: Test docker build
      run: docker build . -t deep-lesion:test-build
